package main

// Generated by https://quicktype.io

type ClusterResponse struct {
	Name                           string                   `json:"name"`
	NodeConfig                     Config                   `json:"nodeConfig"`
	MasterAuth                     MasterAuth               `json:"masterAuth"`
	LoggingService                 string                   `json:"loggingService"`
	MonitoringService              string                   `json:"monitoringService"`
	Network                        string                   `json:"network"`
	ClusterIpv4CIDR                string                   `json:"clusterIpv4Cidr"`
	AddonsConfig                   AddonsConfig             `json:"addonsConfig"`
	Subnetwork                     string                   `json:"subnetwork"`
	NodePools                      []NodePool               `json:"nodePools"`
	Locations                      []string                 `json:"locations"`
	LabelFingerprint               string                   `json:"labelFingerprint"`
	LegacyABAC                     IPAllocationPolicy       `json:"legacyAbac"`
	NetworkPolicy                  IPAllocationPolicy       `json:"networkPolicy"`
	IPAllocationPolicy             IPAllocationPolicy       `json:"ipAllocationPolicy"`
	MasterAuthorizedNetworksConfig IPAllocationPolicy       `json:"masterAuthorizedNetworksConfig"`
	NetworkConfig                  NetworkConfig            `json:"networkConfig"`
	DefaultMaxPodsConstraint       DefaultMaxPodsConstraint `json:"defaultMaxPodsConstraint"`
	SelfLink                       string                   `json:"selfLink"`
	Zone                           string                   `json:"zone"`
	Endpoint                       string                   `json:"endpoint"`
	InitialClusterVersion          string                   `json:"initialClusterVersion"`
	CurrentMasterVersion           string                   `json:"currentMasterVersion"`
	CurrentNodeVersion             string                   `json:"currentNodeVersion"`
	CreateTime                     string                   `json:"createTime"`
	Status                         string                   `json:"status"`
	NodeIpv4CIDRSize               int64                    `json:"nodeIpv4CidrSize"`
	ServicesIpv4CIDR               string                   `json:"servicesIpv4Cidr"`
	InstanceGroupUrls              []string                 `json:"instanceGroupUrls"`
	CurrentNodeCount               int64                    `json:"currentNodeCount"`
	Location                       string                   `json:"location"`
}

type AddonsConfig struct {
	HTTPLoadBalancing        IPAllocationPolicy  `json:"httpLoadBalancing"`
	HorizontalPodAutoscaling IPAllocationPolicy  `json:"horizontalPodAutoscaling"`
	KubernetesDashboard      KubernetesDashboard `json:"kubernetesDashboard"`
	NetworkPolicyConfig      KubernetesDashboard `json:"networkPolicyConfig"`
}

type IPAllocationPolicy struct {
}

type KubernetesDashboard struct {
	Disabled bool `json:"disabled"`
}

type DefaultMaxPodsConstraint struct {
	MaxPodsPerNode string `json:"maxPodsPerNode"`
}

type MasterAuth struct {
	ClusterCACertificate string `json:"clusterCaCertificate"`
}

type NetworkConfig struct {
	Network    string `json:"network"`
	Subnetwork string `json:"subnetwork"`
}

type Config struct {
	MachineType    string   `json:"machineType"`
	DiskSizeGB     int64    `json:"diskSizeGb"`
	OauthScopes    []string `json:"oauthScopes"`
	Metadata       Metadata `json:"metadata"`
	ImageType      string   `json:"imageType"`
	ServiceAccount string   `json:"serviceAccount"`
	Preemptible    bool     `json:"preemptible"`
	DiskType       string   `json:"diskType"`
}

type Metadata struct {
	DisableLegacyEndpoints string `json:"disable-legacy-endpoints"`
}

type NodePool struct {
	Name              string     `json:"name"`
	Config            Config     `json:"config"`
	InitialNodeCount  int64      `json:"initialNodeCount"`
	Management        Management `json:"management"`
	PodIpv4CIDRSize   int64      `json:"podIpv4CidrSize"`
	SelfLink          string     `json:"selfLink"`
	Version           string     `json:"version"`
	InstanceGroupUrls []string   `json:"instanceGroupUrls"`
	Status            string     `json:"status"`
}

type Management struct {
	AutoRepair bool `json:"autoRepair"`
}
